### PR TITLE
Update repo name in docs

### LINKED ISSUE #17: update all links, CI, and website for swig-templates package name/url

### PR DESCRIPTION
**Pull request by Lochlan**
closes #17

### CODE REVIEW

**Comment by cdaringe** [comment]
Nice! +1

**Comment by paulcpederson** [comment]
👍

**Comment by paulcpederson** [comment]
Good news and bad news, looks like Travis is now running this as a Node project (good), but it says our coverage is 0% (bad). @cdaringe do you know how coverage is generated? I'm having this problem locally as well so I can't commit until it's fixed.

**Comment by paulcpederson** [comment]
https://travis-ci.org/node-swig/swig-templates/jobs/156556697

**Pull request merged**
