### PR TITLE
New Documentation

### PR DESCRIPTION
**Pull request by paulcpederson**
@Lochlan @cdaringe This pr is into a new feature branch I created so you guys can check out the work I'm doing on the doc site. 

I am running all of the jsdoc stuff from `package.json` and dumping it in a `data` folder inside docs. That makes it really easy to pull in with the new static site generator. 

If you pull this down and `npm install` you should be able to just `npm run docs` and it will start up a server for you on 8080. This should watch the `lib` and rebuild if you change the jsdoc comments as well.

This also gets us further towards moving away from `Make` entirely. The only things left are building the dist, the testing, and building to gh-pages, which could all probably be accomplished via `package.json`

I also took a stab at updating the CSS/fonts a bit to give the site a little face lift. Let me know what you guys think about this when you get a second.

### CODE REVIEW

**Comment by cdaringe** [comment]
I'm a big fan of the gh-pages package.  Should make the doc publish a walk
in the park!  https://github.com/cdaringe/pouchy/blob/master/package.json
ref deploy-docs.  Obviously it's not xplatform friendly but is a good start!

**Comment by cdaringe** [comment]
@paulcpederson,

- got coverage working again. was going to push to `docs` branch, then merge into yours... foolishly didn't see that there already was a docs branch in `swig-templates`... :)  whatever.
- so, coverage is back, https://travis-ci.org/node-swig/swig-templates/builds/164090583, BUT, the `docs` scripts are still wonky

**Comment by cdaringe** [comment]
@paulcpederson, we can both run off of the `swig-templates#docs` branch to keep this guy alive! opened #29 as a continuation of this effort. at least we're green now :)

**Comment by Lochlan** [comment]
@cdaringe we've been green for a month? https://github.com/node-swig/swig-templates/pull/25

**Comment by cdaringe** [comment]
@lochlan we weren't green specifically on Paul's doc branch

**Comment by cdaringe** [comment]
Oh whoops, biff. Not sure how I didn't see #25!!

**Pull request merged**
