### PR TITLE
Fix Travis build status badge. Remove Gemnasium dependency badge.

### PR DESCRIPTION
**Pull request by pstephenson02**
I'd never heard of Gemnasium before and I'm not sure how valuable it is to have the badge. But if you guys do decide to add swig-templates on there it's easy enough to add the badge back on.

### CODE REVIEW

**Comment by kgarsjo** [comment]
Any chance we can get some momentum on reviewing this one? The `invalid` build badge has been hanging around for a while.

**Comment by cdaringe** [comment]
+1

**Comment by Lochlan** [comment]
Sorry for the delay @pstephenson02 and @kgarsjo.

LGTM, merging.  (Thanks for the second review, @cdaringe)

**Comment by kgarsjo** [comment]
Thanks guys! :+1:

**Pull request merged**
