### PR TITLE
Fixed ReDoS vulnerability

### PR DESCRIPTION
**Pull request by jackhsu978**
See https://nodesecurity.io/advisories/48

### CODE REVIEW

**Comment by Lochlan** [comment]
Looks good to me.

@cdaringe @paulcpederson looks like CI is borked right now.  The build is exiting with a 1.  Looks to me like the failure has to do with coverage reporting.  The first question I have is why we're stringing together four separate commands for our test command (`make lint && make test reporter=spec && make test-browser reporter=spec && make coverage cov-reporter=travis-cov`), which reduces granularity in reporting on CI.  Frankly I think we can probably remove the coverage reporting in CI unless we want to integrate with coveralls or something.

**Comment by paulcpederson** [comment]
@Lochlan yeah, it's reporting that coverage is 0%, which is clearly not true. Should be about 98%. I think we should merge this as all the unit tests pass, and we should open an issue to fix the coverage reporting. I believe @cdaringe did some work in make, maybe it broke at that point?

**Comment by cdaringe** [comment]
sorry there guys.  delayed reply.  my adjustments to the make file netted only to the [eslint conversion](https://github.com/node-swig/swig-templates/pull/12), which was green.  not sure what exactly is causing it to fail, but there are deprecation notices all over which should be patched.  agreed, w/ you both on all issues.

i think public CI is the most honest/trustworthy place to publish coverage from, so perhaps a coveralls conversion is in order.  it's simple enough.

**Comment by cdaringe** [comment]
thanks @jackhsu978 !

**Comment by paulcpederson** [comment]
@cdaringe coveralls is a terrific idea, 💯

**Comment by cdaringe** [comment]
@Lochlan and @paulcpederson, I moved back home. if you guys want to meet up some time (maybe Sunday afternoon), it could be cool to have a 'nice-to-meet-ya' let's kick this thing into gear working session

**Comment by paulcpederson** [comment]
I'm out of town this weekend, but definitely down for an IRL get together/hack session

**Comment by paulcpederson** [comment]
just realized we are all in Oregon, which is pretty weird

**Comment by Lochlan** [comment]
^Definitely funny that we're all in Oregon.  I would be down to meet up.  I'm also busy this weekend, and the next one as well but could potentially do some future weekend.  After work in downtown Portland (I'm in the Pearl but can walk) will generally be the most convenient for me FWIW.

**Comment by cdaringe** [comment]
cool.  i'm at pretty much at hawthorne and the river, westside.  close enough :)

**Pull request merged**
